version: "3.8"

services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
    build: .
    ports:
      - "8181:8181"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/stayhealthybeta1
    restart: always

volumes:
  mongo-data:
